const data = {
  products: [
    {
      _id: "1",
      name: "ONE°",
      category: "BRACTUS",
      image:'/images/write.png',
      price: 1000,
      countInStock: 1,
      brand: "BRACTUS",
      rating: 4.5,
      numReviews: 110,
      description: "High Quality Product",
    },
    {
      _id: "2",
      name: "TWO°",
      category: "BRACTUS",
     image:'/images/mind.png',
      price: 2000,
      countInStock: 1,
      brand: "BRACTUS",
      rating: 5,
      numReviews: 100,
      description: "Powered by bractus",
    },
    {
      _id: "3",
      name: "THREE°",
      category: "BRACTUS",
      image:'/images/laptop.png',
      price: 3000,
      countInStock: 1,
      brand: "BRACTUS",
      rating: 4.5,
      numReviews: 150,
      description: "Powered by bractus",
    },
    {
      _id: "4",
      name: "FOUR°",
      category: "BRACTUS",
      image:'/images/laptop.png',
      price: 4000,
      countInStock: 1,
      brand: "BRACTUS",
      rating: 4.5,
      numReviews: 150,
      description: "Powered by bractus",
    },
    // {
    //   _id: "4",
    //   name: "pant",
    //   category: "pant",
    //   image:'https://amazona.webacademy.pro/images/p4.jpg',
    //   price: 102,
    //   countInStock: 30,
    //   brand: "Nike",
    //   rating: 4.5,
    //   numReviews: 9,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "5",
    //   name: "Slim pant",
    //   category: "Slim",
    //   image:'https://amazona.webacademy.pro/images/p5.jpg',
    //   price: 105,
    //   countInStock: 6,
    //   brand: "Nike",
    //   rating: 3.5,
    //   numReviews: 6,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "6",
    //   name: "formal pant",
    //   category: "pant",
    //   image:'https://amazona.webacademy.pro/images/p6.jpg',
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "7",
    //   name: "Tile worker",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "9",
    //   name: "Painter",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "10",
    //   name: "Balli-Fanti",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "11",
    //   name: "Tuk-Tuk",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "12",
    //   name: "Pickup-Transport",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "13",
    //   name: "Sweeper",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "14",
    //   name: "Kabaadi-wala",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "15",
    //   name: "Gas-cookers",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "16",
    //   name: "Tent-wala",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "17",
    //   name: "Gardener",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "18",
    //   name: "bag-chain",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "19",
    //   name: "Welder-driller",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
    // {
    //   _id: "20",
    //   name: "Mayur-Jug",
    //   category: "Shirts",
    //   image: "",
    //   price: 101,
    //   countInStock: 0,
    //   brand: "Nike",
    //   rating: 1.5,
    //   numReviews: 4,
    //   description: "High Quality Product",
    // },
  ],
};



export default data ;
